name: 🪄 Compile Flutter

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest  # macOS runner needed for iOS build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0
          
      - name: Install dependencies
        run: |
          flutter pub get

      - name: Build iOS App
        run: |
          flutter build ipa --release --no-codesign

      - name: Upload iOS build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-builds
          path: build/ios/*
          #path: /Users/runner/work/PokeKerna/PokeKerna/build/ios/*
