name: 🪄 Compile Flutter

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: macos-latest  # macOS runner needed for iOS build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest'

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Build APK for Android
        run: |
          flutter build apk --release --no-shrink

      - name: Build AppBundle for Android
        run: |
          flutter build appbundle --release

      - name: Build iOS App
        run: |
          flutter build ios --release --no-codesign

      - name: Upload Android build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: android-builds
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/bundle/release/*.aab

      - name: Upload iOS build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ios-builds
          path: build/ios/iphoneos/*.ipa
